name: Android Dev Build
on:
  push:
    branches: ['main'] # Change this to your actual branch name
jobs:
  android-build:
    name: Android Dev Build
    runs-on: self-hosted
    steps:
      - name: Show self-hosted machine information
        run: uname -a
      - name: Cancel previous runs
        uses: styfle/cancel-workflow-action@0.9.1
      - name: Checkout repo from main branch
        uses: actions/checkout@v3
        with:
          ref: main
      - name: Install npm dependency
        run: npm install
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: |
          cd android
          ./gradlew build
      - name: Build Android JS Bundle
        run: |
          npm run package-android
      - name: Delete Android build duplicate assets resource
        run: npm run delete-pics
      - name: Install bundler
        run: |
          cd android
          gem install bundler
      - name: Install gem plugins
        run: |
          cd android
          bundle install
      - name: Run fastlane
        run: |
          cd android
          bundle exec fastlane build_qa
